#Transformation Calculator

##Initial Matrix

In [5]:
import numpy as np

A = np.array([[2, 4, 4, 3, 2],
             [2, 2, 8, 10, 8],
             [1, 1, 1, 1, 1]])

##Translation

In [6]:
#Variabel T adalah matrix translasi dengan x = 3 dam y = 4
T = np.array([[1, 0, 3],
             [0, 1, 4],
             [0, 0, 1]])

Translasi = np.dot(T, A)
print (Translasi)

[[ 5  7  7  6  5]
 [ 6  6 12 14 12]
 [ 1  1  1  1  1]]


##Sharing

In [7]:
#sharing dengan X = 5
ShX = np.array([[1, 5, 0],
                [0, 1, 0],
                [0, 0, 1]])
ShY = np.array([[1, 0, 0],
                [7, 1, 0],
                [0, 0, 1]])

Sh = np.dot(ShY, ShX)
sharing = np.dot(Sh, Translasi)
print(sharing)


[[ 35  37  67  76  65]
 [251 265 481 546 467]
 [  1   1   1   1   1]]


##Scaling

In [8]:
#scaling secara homogen x dan y sebesar 2
Sc = np.array([[2, 0, 0],
               [0, 2, 0],
               [0, 0, 1]])

scaling = np.dot(Sc, sharing)
print(scaling)

[[  70   74  134  152  130]
 [ 502  530  962 1092  934]
 [   1    1    1    1    1]]
